# -*- coding: utf-8 -*-
"""PARSER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ss7vgR1VQqFT3hica6MxfqmjJobdQw8W
"""

import os
import json

from google import genai
from google.genai import types
from pydantic import BaseModel, Field
from typing import List, Optional


class Materia(BaseModel):
    CLAVE: str
    CRE: str
    SEM: str
    UNIDADES_DE_FORMACION: str
    CF_O_REQ: str
    CURSO_O_PLAN: str
    PER: str

class ResumenPeriodo(BaseModel):
    periodo: str
    u_form_cursadas: int
    u_form_plan: int
    reprobadas_fuera: int
    tot: int
    prom: float
    est: str

class CambioCarrera(BaseModel):
    carrera: str
    periodo: str

class KardexCompleto(BaseModel):

    NOMBRE: str
    CARRERA: str
    FECHA_DE_INGRESO: str
    FECHA_DE_EXPEDICION: str
    MATRICULA: str
    SIGLAS: str
    CAMPUS: str
    SEDE: str

    SEMESTRE_DE_INTRODUCCION: List[Materia]
    PRIMER_SEMESTRE: List[Materia]
    SEGUNDO_SEMESTRE: List[Materia]
    TERCER_SEMESTRE: List[Materia]
    CUARTO_SEMESTRE: List[Materia]
    QUINTO_SEMESTRE: List[Materia]
    SEXTO_SEMESTRE: List[Materia]
    SEPTIMO_SEMESTRE: List[Materia]
    OCTAVO_SEMESTRE: List[Materia]

   
    Semanas_Tec_Obligatoria: List[Materia]
    Semanas_Tec_Optativas: List[Materia]

    Semanas_Tec_Complementarias: List[Materia]
    Unidades_de_Formacion_No_Reprobadas_Fuera_del_Plan: List[Materia]
    Actividades_Formativas: List[Materia]
    Examen_de_Admision: List[Materia]

 
    RESUMEN_ACADEMICO: List[ResumenPeriodo]
    Creditos_del_plan_totales: float
    Creditos_del_plan_acreditados: float
    Creditos_del_plan_pendientes: float
    Unidades_de_Formacion_del_plan_totales: int
    Unidades_de_Formacion_del_plan_acreditadas: int
    Unidades_de_Formacion_del_plan_pendientes: int
    Promedio_acumulado_plan: str
    Semestre_acreditado: str
    Estatus_academico_del_alumno: str
    Creditos_permitidos_a_inscribir: int
    Horas_de_Servicio_Social: int
    Cambios_de_carrera: List[CambioCarrera]


def extraer_kardex_a_json(ruta_imagen_3: str,ruta_imagen_4: str, ruta_salida_json: str):

    client = genai.Client()


    img_3 = client.files.upload(file=ruta_imagen_3)
    img_4 = client.files.upload(file=ruta_imagen_4)

    prompt = """
    Extrae de forma exhaustiva y precisa el 100% de la información contenida en las dos imágenes del Kardex.
    Asegúrate de mapear cada materia en su semestre o sección correspondiente (Semestre de Introducción, Primer Semestre hasta Octavo,
    Semanas Tec Obligatorias y Optativas).
    Respeta exactamente los nombres de los campos requeridos en el esquema.
    """


    response = client.models.generate_content(
        model='gemini-3.6-flash', 
        contents=[img_3,img_4,prompt],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=KardexCompleto,
            temperature=0.1
        ),
    )


    datos_extraidos = json.loads(response.text)

    with open(ruta_salida_json, "w", encoding="utf-8") as f:
        json.dump(datos_extraidos, f, ensure_ascii=False, indent=4)

    print(f"Extracción completada con éxito. Archivo guardado en: {ruta_salida_json}")

MIS_LLAVES = [ "","","","",""]


kardex_entries = [
    
    {
        "img3_path": "/content/IDM19_anonimizado_page-0001.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0002.jpg",
        "output_json_name": "IDM_1.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0003.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0004.jpg",
        "output_json_name": "IDM_2.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0005.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0006.jpg",
        "output_json_name": "IDM_3.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0007.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0008.jpg",
        "output_json_name": "IDM_4.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0009.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0010.jpg",
        "output_json_name": "IDM_5.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0011.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0012.jpg",
        "output_json_name": "IDM_6.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0013.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0014.jpg",
        "output_json_name": "IDM_7.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0015.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0016.jpg",
        "output_json_name": "IDM_8.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0017.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0018.jpg",
        "output_json_name": "IDM_9.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0019.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0020.jpg",
        "output_json_name": "IDM_10.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0021.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0022.jpg",
        "output_json_name": "IDM_11.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0023.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0024.jpg",
        "output_json_name": "IDM_12.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0025.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0026.jpg",
        "output_json_name": "IDM_13.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0027.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0028.jpg",
        "output_json_name": "IDM_14.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0029.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0030.jpg",
        "output_json_name": "IDM_15.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0031.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0032.jpg",
        "output_json_name": "IDM_16.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0033.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0034.jpg",
        "output_json_name": "IDM_17.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0035.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0036.jpg",
        "output_json_name": "IDM_18.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0037.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0038.jpg",
        "output_json_name": "IDM_19.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0039.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0040.jpg",
        "output_json_name": "IDM_20.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0041.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0042.jpg",
        "output_json_name": "IDM_21.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0043.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0044.jpg",
        "output_json_name": "IDM_22.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0045.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0046.jpg",
        "output_json_name": "IDM_23.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0047.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0048.jpg",
        "output_json_name": "IDM_24.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0049.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0050.jpg",
        "output_json_name": "IDM_25.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0051.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0052.jpg",
        "output_json_name": "IDM_26.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0053.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0054.jpg",
        "output_json_name": "IDM_27.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0055.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0056.jpg",
        "output_json_name": "IDM_28.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0057.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0058.jpg",
        "output_json_name": "IDM_29.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0059.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0060.jpg",
        "output_json_name": "IDM_30.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0061.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0062.jpg",
        "output_json_name": "IDM_31.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0063.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0064.jpg",
        "output_json_name": "IDM_32.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0065.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0066.jpg",
        "output_json_name": "IDM_33.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0067.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0068.jpg",
        "output_json_name": "IDM_34.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0069.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0070.jpg",
        "output_json_name": "IDM_35.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0071.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0072.jpg",
        "output_json_name": "IDM_36.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0073.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0074.jpg",
        "output_json_name": "IDM_37.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0075.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0076.jpg",
        "output_json_name": "IDM_38.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0077.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0078.jpg",
        "output_json_name": "IDM_39.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0079.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0080.jpg",
        "output_json_name": "IDM_40.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0081.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0082.jpg",
        "output_json_name": "IDM_41.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0083.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0084.jpg",
        "output_json_name": "IDM_42.json"
    },

    {
        "img3_path": "/content/IDM19_anonimizado_page-0085.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0086.jpg",
        "output_json_name": "IDM_43.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0087.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0088.jpg",
        "output_json_name": "IDM_44.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0089.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0090.jpg",
        "output_json_name": "IDM_45.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0091.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0092.jpg",
        "output_json_name": "IDM_46.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0093.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0094.jpg",
        "output_json_name": "IDM_47.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0095.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0096.jpg",
        "output_json_name": "IDM_48.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0097.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0098.jpg",
        "output_json_name": "IDM_49.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0099.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0100.jpg",
        "output_json_name": "IDM_50.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0101.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0102.jpg",
        "output_json_name": "IDM_51.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0103.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0104.jpg",
        "output_json_name": "IDM_52.json"
    },
    {
        "img3_path": "/content/IDM19_anonimizado_page-0105.jpg",
        "img4_path": "/content/IDM19_anonimizado_page-0106.jpg",
        "output_json_name": "IDM_53.json"
    }

]

successfully_processed_jsons = set()
overall_success = False

for llave in MIS_LLAVES:
    os.environ["GEMINI_API_KEY"] = llave
    print(f"Attempting with API Key: {llave[:10]}...") 

    current_key_succeeded_on_all_remaining = True

    for entry in kardex_entries:
        current_img3_path = entry["img3_path"]
        current_img4_path = entry["img4_path"]
        current_output_json_name = entry["output_json_name"]

        if current_output_json_name in successfully_processed_jsons:
            print(f"Skipping {current_output_json_name} as it was already processed.")
            continue

        try:
            print(f"Processing Kardex from {current_img3_path}, {current_img4_path} to {current_output_json_name}")
            extraer_kardex_a_json(current_img3_path, current_img4_path, current_output_json_name)
            print(f"Successfully processed {current_output_json_name}")
            successfully_processed_jsons.add(current_output_json_name)
        except Exception as e:
            print(f"This key failed or encountered an error for {current_output_json_name}: {e}. Trying the next key...")
            current_key_succeeded_on_all_remaining = False
            break 

    if current_key_succeeded_on_all_remaining and len(successfully_processed_jsons) == len(kardex_entries):
        overall_success = True
        print(f"¡All extractions completed successfully using the key: {llave[:10]}...!")
        break 
    elif current_key_succeeded_on_all_remaining and len(successfully_processed_jsons) < len(kardex_entries):
        
        print(f"API Key {llave[:10]}... successfully processed all remaining items. Moving to next key if any files are still unprocessed.")

if not overall_success:
    print(f"No se pudo completar la extracción para todos los archivos con ninguna de las llaves proporcionadas. Processed {len(successfully_processed_jsons)} out of {len(kardex_entries)} files.")
else:
    print("All Kardex files processed successfully.")
